### ISSUE TITLE
Game Build v1.0 Game Testing  Mega-Thread.

### ISSUE THREAD

**Issue by ghost** [Makas9/Project-Delta-Strike#17]
Here's all the bugs I have found in game testing:

- Go to store button not visible on 1080p resolution.
- Level 3 has a floating white box right before the fall.
- After completing Level 5 you're greeted with an unfinished level black screen.
- Pressing play right after login brings you to an unfinished level (Level 6 presumably).
- Knife rate of fire tied to primary rate of fire.
- If you enter the inventory your equipped items will light up all the items with the same name. 
- Thompson has the shotgun range and rate of fire of a shotgun or 870.
- You are able to complete a level after you've died.
- You are able to die after completing a level. (Loads you into the same level.)
- I am unable to scroll down to choose level 5 in level select screen. (Touch screen controls???)

Here's all the balance changes I'd do:

- Increase 870_MCS, Shotgun and RPG rate of fire and damage.
- Reduce the cost of knives.
- Make helmets and vests have different costs.

**Comment by K0ST4S** [comment]
Go to store button not visible on 1080p resolution: fixed in 11d4ce0a4b4bafd5d97bf6484d074db1490853a3 commit
I am unable to scroll down to choose level 5 in level select screen: : fixed in 11d4ce0a4b4bafd5d97bf6484d074db1490853a3 commit
You can do all of these by adjusting Json file settings in our database:
Thompson has the shotgun range and rate of fire of a shotgun or 870.
Increase 870_MCS, Shotgun and RPG rate of fire and damage.
Reduce the cost of knives.
Make helmets and vests have different costs.

**Comment by ghost** [comment]
Roger that, I'm on it.
